#!/bin/sh
set -eu

cd "${0%/*}/.."

if [[ -e tkey-sign ]]; then
  if ! go version -m tkey-sign | grep -q main.signerAppNoTouch=indeed; then
    printf "We need to build with the touch requirement removed.\n"
    printf "Please first do: make -C ../ clean\n"
    exit 1
  fi
fi
make TKEY_SIGNER_APP_NO_TOUCH=indeed -C apps
make TKEY_SIGNER_APP_NO_TOUCH=indeed tkey-runapp tkey-sign

cd "test"

if [ ! -e venv ]; then
  python3 -m venv venv
  . ./venv/bin/activate
  pip3 install -r requirements.txt
else
  . ./venv/bin/activate
fi

./test-loop.py
