#!/bin/bash
set -eu

tag="SPDX-License-Identifier:"

dirsok=(
.github/workflows/
LICENSES/
debian/
docs/
)

filesok=(
.clang-format
.editorconfig
.gitignore
.golangci.yml
Makefile
README.md
apps/Makefile
apps/monocypher/LICENSE
apps/monocypher/README.md
apps/rng_stream/README.md
apps/signer/runsign.sh
dco.md
go.mod
go.sum
gotools/Makefile
gotools/go.mod
gotools/go.sum
system/60-tkey.rules
system/90-tkey-ssh-agent.rules
system/tkey-ssh-agent.1
system/tkey-ssh-agent.service.tmpl
test/test-loop.sh
)

is_missingok() {
  item="$1"
  # ok for empty files
  [[ -f "$item" ]] && [[ ! -s "$item" ]] && return 0
  for fileok in "${filesok[@]}"; do
    [[ "$item" = "$fileok" ]] && return 0
  done
  for dirok in "${dirsok[@]}"; do
    [[ "$item" =~ ^$dirok ]] && return 0
  done
  return 1
}

printf "* Checking for SPDX tags in %s\n" "$PWD"

mapfile -t repofiles < <(git ls-files || true)
if [[ -z "${repofiles[*]}" ]]; then
  printf "* No files in the repo?!\n"
  exit 1
fi

failed=0

printed=0
for fileok in "${filesok[@]}"; do
  [[ -f "$fileok" ]] && continue
  if (( !printed )); then
    printf "* Some files in filesok are themselves missing:\n"
    printed=1
    failed=1
  fi
  printf "%s\n" "$fileok"
done

printed=0
for dirok in "${dirsok[@]}"; do
  [[ -d "$dirok" ]] && continue
  if (( !printed )); then
    printf "* Some dirs in dirsok are themselves missing:\n"
    printed=1
    failed=1
  fi
  printf "%s\n" "$dirok"
done

printed=0
for file in "${repofiles[@]}"; do
  is_missingok "$file" && continue
  if ! grep -q "$tag" "$file"; then
    if (( !printed )); then
      printf "* Files missing the SPDX tag:\n"
      printed=1
      failed=1
    fi
    printf "%s\n" "$file"
  fi
done

exit "$failed"
