#!/bin/sh
# SPDX-FileCopyrightText: 2022 Tillitis AB <tillitis.se>
# SPDX-License-Identifier: BSD-2-Clause

set -e

case "$1" in
    configure)
        if udevadm --version >/dev/null; then
            udevadm control --reload || true
            udevadm trigger --action=add --subsystem-match=tty || true
        fi
    ;;
esac
